Repository azavea/idb-osm-extraction-tool, pull requests merged in 2019-03, with the labels that each got.

#42 adds additional keys and values
  src/js/src/featureConfig.js
Labels: in progress

#44 Small improvements
  src/js/src/components/ExtractButton.jsx
  src/js/src/components/OSMExtractionMap.jsx
  src/js/src/constants.js
Labels: in progress

#45 Add missing year to LICENSE.md
  LICENSE.md
Labels: queue

#46 Conform README to IDB template
  README.md
Labels: in review

#47 Add Netlify build status badge to README
  README.md
Labels: in progress

#48 Update the license section of the README
  README.md
Labels: in progress
